- name: Install Samba Server and Configure Samba User
  hosts: web
  become: yes
  vars_prompt:
    - name: "smb_password"
      prompt: "Please enter the password for the Samba user"
      private: yes  # 비밀번호를 숨김 처리

  tasks:
    - name: Install Samba packages
      apt:
        name:
          - samba
          - samba-common
          - smbclient
        state: present
        update_cache: yes

    - name: Ensure Samba service is started and enabled
      service:
        name: smbd
        state: started
        enabled: yes

    - name: Create samba user (user2)
      user:  
        name: user2
        password: "{{ 'smb_password' | password_hash('sha512') }}"
        state: present

    # 4. Add Samba user to Samba database
    - name: Add Samba user to Samba database
      command: echo -e "{{ smb_password }}\n{{ smb_password }}" | smbpasswd -a -s smbuser
      args:
        creates: /etc/samba/smbpasswd
      become: yes

    # 5. Enable Samba user (smbuser)
    - name: Enable Samba user (smbuser)
      command: smbpasswd -e smbuser
      become: yes
      when: ansible_facts.packages['samba'] is defined

    - name: Configure Samba share in smb.conf
      blockinfile:
        path: /etc/samba/smb.conf
        marker: "# {ansible_managed} #"
        block: |
          [humans2]
          path = /humans2
          browseable = yes
          read only = no
          guest ok = yes
          create mask = 0777
          directory mask = 0777

    - name: Create shared directory for Samba
      file:
        path: /humans2
        state: directory
        owner: root
        group: user2
        mode: '0777'

    - name: Set correct permissions for Samba shared directory
      file:
        path: /humans2
        recurse: yes
        owner: user2
        group: user2
        mode: '0777'
