- name: Install and configure Nginx with 2 virtual hosts on Ubuntu
  hosts: web
  become: yes
  tasks:
    # 1. Nginx 설치
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
    # 7. Nginx 재시작
    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
